[package]
name = "cli-message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.82"
quote = "1.0.36"
syn = "2.0.63"

[lib]
proc-macro = true
